### ISSUE TITLE
Some classes with double entries

### ISSUE THREAD

**Issue by kaig78** [albertc44/peloton-coda-sync#1]
Hi, thank you for developing this great tool to analyze the outputs. I re-run the script via Google Daily according to the instructions but the same data doubles each day. Can you add a line that deletes the data before adding or checks which data to add? Thank you.

**Comment by thealchen** [comment]
Hi @kaig78, the script actually checks to see what existing workouts are in your Coda doc (the `Workout ID` column). As long as that column contains data, every time the script runs you should only get _new_ workouts added to the main "Workouts" table. Do you see duplicate `Workout ID`s in the "Workouts table?"

**Comment by kaig78** [comment]
Hi @albertc44 yes, I do. However it is not all the classes. Let me try to delete everything again and wait another day or two. Thank you for checking and once again thank you for this great script.

**Comment by thealchen** [comment]
@kaig78 Sounds good. I have the script running weekly and it works fine, so as long as you didn't edit other parts of the script it should work as intended.

**Comment by kaig78** [comment]
Hi @albertc44 after some days trying, I can say it still happens. But strangely not for all classes taken. I deleted the data several times and started again. Still after 2 days of the script running, many classes would show twice. Any idea to solve this?

**Comment by thealchen** [comment]
@kaig78 This is strange I haven't seen anyone else have this error. Do you want to email me at al@coda.io and I can help you debug? It would be great if you can share a screenshot of your "Workouts" table so I can see how the IDs are repeating. If you can also share the Google App Script you're using (remove any sensitive info) that would be great as well.

**Comment by kaig78** [comment]
Send it to you. Thank you again for your kindness. Would be great if you can have a quick look. 
<img width="792" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/5559310/107856656-e7680300-6e29-11eb-9b95-f16eae39c055.png">

**Comment by thealchen** [comment]
This issues appears to have been solved with the latest updates to the script (Feb 27, 2021).
