### ISSUE TITLE
Error when running Google Script

### ISSUE THREAD

**Issue by ctho725** [albertc44/peloton-coda-sync#2]
Hey there, thank you so much for making this!
I'm getting the following error when I run the script:
![image](https://user-images.githubusercontent.com/65498384/108786090-1ccfc780-7573-11eb-95e3-b991af7ced08.png)
Any tips for what to do here?

**Comment by thealchen** [comment]
Looks like this got solved per this YouTube comment [here](https://www.youtube.com/watch?v=L4llF9Wq58A&lc=UgyzoJkuwhy46UBvpH54AaABAg.9Jij2ZkuS0x9K4lrrM2fye).

**Comment by ctho725** [comment]
This was a different problem! I fixed this and was able to run the program (I couldn't run it at all before), but now I'm getting the error I posted above. Sorry for the confusion!

**Comment by thealchen** [comment]
Ah sorry about that! Looks like you might have done a workout that doesn't have ratings and it's a workout type I didn't account for (I was only able to test with biking, running, strength, and meditation workouts). Without seeing the details of your script, I would delete line 87 from the script for now. This the line you should delete:

```javascript
{'column': 'Total Ratings',         'value': workoutData[workout]['summary']['ride']['overall_rating_count']},
```

Try running the script with that line removed and see if it works!

**Comment by ctho725** [comment]
I do also have cardio and yoga. I was previously just using the app before getting the bike so I do have cycling classes with no metrics. I'm not sure if that causes an issue.

Line 87 for me is 
`{'column': 'Avg Resistance', 'value': workoutData[workout]['performance']['average_summaries'][2]['value']},
`
but removing that doesn't help, nor does removing the line you suggested (77).

**Comment by thealchen** [comment]
@ctho725 I just made some edits and did a few tests and believe the new script works now. Copy and paste the script from [here](https://github.com/al-codaio/peloton-coda-sync/blob/master/peloton_coda_gas.js). Going to close this issue for now unless you come across the issue again!

**Comment by ctho725** [comment]
Thank you for all your work! Unfortunately I'm still getting a similar error.

![image](https://user-images.githubusercontent.com/65498384/109405002-12933c00-796c-11eb-9267-8e4c0757c3d5.png)

**Comment by thealchen** [comment]
Very strange. Can you copy and paste line 79 from your script here?

**Comment by ctho725** [comment]
![image](https://user-images.githubusercontent.com/65498384/109405496-65bbbd80-7971-11eb-8b71-c4565cf95e1a.png)

**Comment by thealchen** [comment]
Hm that's really strange, must be some weird edge case. Right below the line where it says `for (workout in workoutData) {`, can you put the following code and run the script? This will help me figure out which workout might be causing problems:

```javascript
Logger.log(prettyPrint(workout))
```

After you run the script, you'll see a bunch of workout IDs getting printed to the bottom panel (Execution Log) in your screen. Let me know what the last workout ID you see is before it gives you an error.

**Comment by thealchen** [comment]
@ctho725 Were you able to add that line of code to test which workout might be causing problems? My hunch is that there is a specific type of workout that you did which the script doesn't account for that I need to investigate.

**Comment by ctho725** [comment]
I just tried it. Here is the end, before the error. Is that what you need?
![image](https://user-images.githubusercontent.com/65498384/109541006-8d229f80-7ac3-11eb-82cf-3c6238824a92.png)

**Comment by thealchen** [comment]
@ctho725 Thanks, I think I found the error (mistake on my end) and updated the script. Try copying/pasting the script again and let me know if you still run into issues. Btw, I updated [the template](https://coda.io/@atc/analyze-your-peloton-workout-stats-with-real-time-updates) a little bit to include friends' workouts.

**Comment by ctho725** [comment]
It works! Thank you so much for all the work, it's wonderful!

**Comment by ctho725** [comment]
Just some additional feedback for you:

The monthly cycling stats doesn't seem to be working. As you can see above it's definitely reading them but they're not showing up in this table. Can I fix that somehow?
![image](https://user-images.githubusercontent.com/65498384/109725668-c3d6e380-7bb1-11eb-928d-8fa793d633e7.png)

**Comment by thealchen** [comment]
@ctho725 Great to hear it works! For the monthly stats, I made a mistake with the dates in the `Month` column. If you click on each month in 2021, you'll notice it's an actual date that got set to the 28th for some reason. Just click on each month and set the date to the beginning of the month like this and it should calculate correctly:

![Screen Recording 2021-03-02 at 06 51 06 PM](https://user-images.githubusercontent.com/1314187/109731034-8447d180-7b88-11eb-957f-29d15333ad03.gif)
