### ISSUE TITLE
Google Apps Script Error

### ISSUE THREAD

**Issue by bwb289** [albertc44/peloton-coda-sync#3]
When I run the Apps script I get the following error in the execution log. My personal rides come over but none of my friends rides do.

Exception: Request failed for https://coda.io returned code 400. Truncated server response: {"statusCode":400,"statusMessage":"Bad Request","message":"Could not find column \"Username\" within the table."} (use muteHttpExceptions option to examine full response)
upsertRows	@ Coda.gs:495

**Comment by bwb289** [comment]
I was able to resolve this issue by updated the column name in line 202 to 'Peloton Username' instead of 'Username'. It appears the Coda column was changed to 'Peloton Username' at some point.

**Comment by thealchen** [comment]
Thanks for catching this. I edited the template so that the column is `Username` instead of `Peloton Username`.
