### ISSUE TITLE
Google Apps Script Error 

### ISSUE THREAD

**Issue by Jo9871** [albertc44/peloton-coda-sync#4]
When I try to run the script I get this error and the entire script stops working:

12:32:01 PM	Error	
TypeError: cookie.join is not a function
auth	@ Code.gs:241
(anonymous)	@ Code.gs:19

**Comment by thealchen** [comment]
Hi @Jo9871, I've never seen this error before. Just confirming you're using the [V8 runtime](https://developers.google.com/apps-script/guides/v8-runtime) and entering in your Peloton username/pw correctly in the script?

**Comment by Jo9871** [comment]
Thanks for the reply @al-codaio, After checking that I had entered my user name and PW correctly I have noticed that I accidentally added a space after my username and not realized until now, it does now seem to be working.
Sorry for the inconvenience.
Thanks, Josh
